export const services = [
    {
        id: 1,
        imgSrc: '/images/usergroup.png',
        name: 'Пр тр',
        type: 'Группа.',
        traficShow: '-',
        traficClick: 1716,
        traficSessions: 1716,
        traficCTR: '-',
        traficPriceClick: 0,
        traficExpenses: 0,
        salesNumber: 344.54,
        salesCPA: 0,
        salesProceeds: 6778703,
        targetNumber: 29,
        targetCPA: 0,
        targetCR: 10
    },
    {
        id: 2,
        name: 'Яндекс Директ',
        imgSrc: '/images/favicon.ico',
        type: 'Платная реклама',
        traficShow: 299571,
        traficClick: 843,
        traficSessions: 1388,
        traficCTR: 0.28,
        traficPriceClick: 35.9,
        traficExpenses: 30266,
        salesNumber: 181.64,
        salesCPA: 1612,
        salesProceeds: 423719,
        targetNumber: 23,
        targetCPA: 11,
        targetCR: 32
    },
    {
        id: 3,
        name: 'Органический поиск',
        imgSrc: '/images/search.png',
        type: 'Группа.',
        traficShow: '-',
        traficClick: 843,
        traficSessions: 1388,
        traficCTR: 0.28,
        traficPriceClick: 35.9,
        traficExpenses: 30266,
        salesNumber: 181.64,
        salesCPA: 1612,
        salesProceeds: 423719,
        targetNumber: 23,
        targetCPA: 11,
        targetCR: 32
    },
    {
        id: 4,
        name: 'Google Ads',
        imgSrc: '/images/google.png',
        type: 'Платная реклама',
        traficShow: 5272,
        traficClick: 252,
        traficSessions: 449,
        traficCTR: 4.78,
        traficPriceClick: 58.77,
        traficExpenses: 14809,
        salesNumber: 107.13,
        salesCPA: 135,
        salesProceeds: 2429134,
        targetNumber: 10,
        targetCPA: 14,
        targetCR: 38
    },
    {
        id: 5,
        name: 'Переходы с сайтов',
        imgSrc: '/images/chain.png',
        type: 'Группа.',
        traficShow: '-',
        traficClick: 220,
        traficSessions: 220,
        traficCTR: '-',
        traficPriceClick: 0,
        traficExpenses: 0,
        salesNumber: 55.11,
        salesCPA: 0,
        salesProceeds: 109487,
        targetNumber: 4,
        targetCPA: 0,
        targetCR: 18
    },
    {
        id: 6,
        name: 'Email-рассылки',
        imgSrc: '/images/e-mail.ico',
        type: 'Группа.',
        traficShow: '-',
        traficClick: 84,
        traficSessions: 84,
        traficCTR: '-',
        traficPriceClick: 75,
        traficExpenses: 6300,
        salesNumber: 15.11,
        salesCPA: 210,
        salesProceeds: 28614.4,
        targetNumber: 2,
        targetCPA: 3,
        targetCR: 25,
        sources: [
            {
                id: 11,
                name: 'e-mail / e-mail',
                imgSrc: '/images/e-mail.ico',
                traficShow: '-',
                traficClick: 81,
                traficSessions: 81,
                traficCTR: '-',
                traficPriceClick: 39.51,
                traficExpenses: 3200,
                salesNumber: 15.21,
                salesCPA: 215,
                salesProceeds: 2168,
                targetNumber: 2,
                targetCPA: 135,
                targetCR: 25, 
            },
            {
                id: 12,
                name: 'videocourse / e-mail',
                imgSrc: '/images/e-mail.ico',
                traficShow: '-',
                traficClick: 2,
                traficSessions: 2,
                traficCTR: '-',
                traficPriceClick: 0,
                traficExpenses: 0,
                salesNumber: 0,
                salesCPA: 0,
                salesProceeds: 0,
                targetNumber: 0,
                targetCPA: 0,
                targetCR: 0, 
            },
            {
                id: 13,
                name: 'getresponse / e-mail',
                imgSrc: '/images/getresponse.ico',
                traficShow: '-',
                traficClick: 1,
                traficSessions: 1,
                traficCTR: '-',
                traficPriceClick: 0,
                traficExpenses: 0,
                salesNumber: 0,
                salesCPA: 0,
                salesProceeds: 0,
                targetNumber: 0,
                targetCPA: 0,
                targetCR: 0, 
            },
            {
                id: 14,
                name: 'cm / e-mail',
                imgSrc: '/images/cm.ico',
                traficShow: '-',
                traficClick: 0,
                traficSessions: 0,
                traficCTR: '-',
                traficPriceClick: 0,
                traficExpenses: 0,
                salesNumber: 0,
                salesCPA: 0,
                salesProceeds: 0,
                targetNumber: 0,
                targetCPA: 0,
                targetCR: 0, 
            },
            {
                id: 15,
                name: 'e-mail/ course',
                imgSrc: '/images/e-mail.ico',
                traficShow: '-',
                traficClick: 0,
                traficSessions: 0,
                traficCTR: '-',
                traficPriceClick: 0,
                traficExpenses: 3100,
                salesNumber: 0,
                salesCPA: 0,
                salesProceeds: 0,
                targetNumber: 0,
                targetCPA: 0,
                targetCR: 0, 
            },
        ]
    },

]

export const total = {
    trafic: {
        show: 327872,
        click: 6889,
        sessions: 5325,
        CTR: 2.1,
        priceClick: 11.06,
        expenses: 76195,
    },
    sales: {
        number: 1047.93,
        CPA: 72465,
        proceeds: 21509634.4
    },
    target: {
        number: 89,
        CPA: 8516,
        CR: 18
    }
}